version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: internetmarke
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev